package com.dslfoundry.statemachine.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int Event = 1;
  public static final int Guard = 2;
  public static final int State = 3;
  public static final int StateMachine = 4;
  public static final int Transition = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xdac36cdfb92546cfL, 0x8a2c2b6a1b73035cL);
    builder.put(0x7ad27988f18a0f9cL, Action);
    builder.put(0x51c6850f8a2fce2dL, Event);
    builder.put(0x7ad27988f18a14bdL, Guard);
    builder.put(0x51c6850f8a2fce2cL, State);
    builder.put(0x51c6850f8a2fce29L, StateMachine);
    builder.put(0x51c6850f8a2fce2eL, Transition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
